services:
  bitwarden-backup:
    container_name: bitwarden-backup
    build: .
    env_file: .env
    environment:
      TZ: ${TZ:-America/New_York}
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      INTERVAL: ${INTERVAL:-24h}
      BACKUP_ORGANIZATION_ONLY: ${BACKUP_ORGANIZATION_ONLY:-False}
    volumes:
      - ./data/:/data/