services:
  bitwarden-backup:
    container_name: bitwarden-backup
    build: .
    #env_file: .env
    environment:
      TZ: America/Manaus
      UID: ${UID:-1000}
      GID: ${GID:-1000}
      INTERVAL: ${INTERVAL:-24h}
      BW_SERVER: ${BW_SERVER}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      MASTER_PASSWORD: ${MASTER_PASSWORD}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      
    volumes:
      - ./data/:/data/