name: Push image tag alpine to docker hub

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile.alpine'
      - 'src/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile.alpine'
      - 'src/**'

env:
  PLATAFORM_ARCH: linux/amd64
  CONTAINER_REPO: ${{ vars.DOCKERHUB_USERNAME }}/bitwarden-backup
  
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATAFORM_ARCH }}
                
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ env.PLATAFORM_ARCH }}
          push: true
          tags: ${{ env.CONTAINER_REPO }}:alpine
